server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Routes Configuration
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**, /api/users/**, /api/drivers/**

spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=http://payment-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/payments/**

spring.cloud.gateway.routes[2].id=ride-service
spring.cloud.gateway.routes[2].uri=http://ride-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/rides/**

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
